gains:
  horizontal:
    kp: 0.15
    kv: 0.15
    ka: 1.0

    kib: 0.01
    kib_lim: 0.15

    kiw: 0.01
    kiw_lim: 0.3

    mute_coefficitent: 0.0

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

weight_estimator:
  km: 1.0
  km_lim: 1.0 # [kg]

g : 9.8

max_tilt_angle: 30.0 # [deg]

yaw_offset: 0.0 # [deg]

gains_filter:
  filter_rate: 10 # [Hz]
  perc_change_rate: 1.0
  min_change_rate: 0.3 # perc of the differnece
