default_gains:

  # Gains in this file should not be changed, since they are not used most of the times.
  # Gains which are actually used are in the MrsMavManager package under the GainManager configs

  horizontal:
    kp: 0.15
    kv: 0.15
    ka: 1.0

    kib: 0.05
    kib_lim: 0.15

    kiw: 0.05
    kiw_lim: 0.3

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 1.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

lateral_mute_coefficitent: 0.0

max_tilt_angle: 90.0 # [deg]

yaw_offset: 0.0 # [deg]

gains_filter:
  filter_rate: 20 # [Hz]
  perc_change_rate: 1.0
  min_change_rate: 0.1 # perc of the difference
