default_gains:

  # Gains in this file should not be changed, since they are not used most of the times.
  # Gains which are actually used are in the MrsMavManager package under the GainManager configs

  horizontal:
    kp: 40.0
    kv: 10.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.5
    kib_lim: 1.0

    kiw: 0.5
    kiw_lim: 1.0

  vertical:
    kp: 150.0
    kv: 70.0
    ka: 1.0

    attitude:
      kq: 20.0
      kw: 5.0

  weight_estimator:
    km: 1.0
    km_lim: 2.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

lateral_mute_coefficitent: 0.0

max_tilt_angle: 90.0 # [deg]

yaw_offset: 0.0 # [deg]

gains_filter:
  filter_rate: 20 # [Hz]
  perc_change_rate: 1.0
  min_change_rate: 0.1 # perc of the difference
