default_gains:

  # Gains in this file SHOULD NOT BE CHANGED, since they are not used most of the times.
  # Gains which are actually used are in the MavManager package under the GainManager configs

  horizontal:
    kp: 1.333333
    kv: 0.833333
    ka: 1.0

    attitude:
      kq: 5.0
      kw: 0.0

    kib: 0.5
    kib_lim: 1.0

    kiw: 0.5
    kiw_lim: 1.0

  vertical:
    kp: 13.333333
    kv: 6.666667
    ka: 1.0

    attitude:
      kq: 2.0
      kw: 2.0

  weight_estimator:
    km: 1.0
    km_lim: 2.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

lateral_mute_coefficitent: 0.0

# saturations and limits
tilt_angle_saturation: 60.0 # [deg], disabled when 0.0
tilt_angle_failsafe: 90.0 # [deg], disabled when 0.0
thrust_saturation: 0.85 # [-], range from 0 to 1

yaw_offset: 0.0 # [deg]

gains_filter:
  filter_rate: 20 # [Hz]
  perc_change_rate: 1.0
  min_change_rate: 0.1 # perc of the difference

# output mode to PixHawk
output_mode: 1 # {1 = attitude_rate, 2 = attitude quaternion}
