default_gains:

  # influences pitching and rolling
  horizontal:
    
    attitude:
      kq: 8.0
      kw: 0.0

  # influences yawing
  vertical:
    kp: 10.0
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.1

  weight_estimator:
    km: 1.0
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
