default_gains:

  # Gains in this file should not be changed, since they are not used most of the times.
  # Gains which are actually used are in the mrs_uav_manager package under the gain_manager configs

  horizontal:
    kp: 3.0
    kv: 1.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.2
    kib_lim: 10.0

    kiw: 0.2
    kiw_lim: 10.0

  vertical:
    kp: 17.0
    kv: 8.0
    ka: 1.0

    attitude:
      kq: 1.0
      kw: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

lateral_mute_coefficitent: 0.0

# saturations and limits
tilt_angle_saturation: 60.0 # [deg], disabled when 0.0
tilt_angle_failsafe: 90.0 # [deg], disabled when 0.0
thrust_saturation: 0.85 # [-], range from 0 to 1

gains_filter:
  filter_rate: 20 # [Hz]
  perc_change_rate: 1.0
  min_change_rate: 0.1 # perc of the difference

# output mode to PixHawk
output_mode: 1 # {1 = attitude_rate, 2 = attitude quaternion}
