integral_gains:

  kiw: 0.1
  kib: 0.1

  kiw_lim: 10.0
  kib_lim: 10.0

attitude_vertical_feedback:

  default_gains:

    horizontal:
      attitude:
        kq: 6.0
        kw: 0.0

    vertical:
      attitude:
        kq: 1.0
        kw: 0.0
