default_gains:

  # Gains in this file should not be changed, since they are not used most of the times.
  # Gains which are actually used are in the MavManager package under the GainManager configs

  horizontal:
    kp: 1.3
    kv: 0.9
    ka: 1.0

    attitude:
      kq: 5.0
      kw: 0.0

    kib: 0.1
    kib_lim: 1.0

    kiw: 0.1
    kiw_lim: 1.0

  vertical:
    kp: 8.6
    kv: 4.3
    ka: 1.0

    attitude:
      kq: 5.0
      kw: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 2.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

lateral_mute_coefficitent: 0.0

max_tilt_angle: 30.0 # [deg]

yaw_offset: 0.0 # [deg]

gains_filter:
  filter_rate: 20 # [Hz]
  perc_change_rate: 1.0
  min_change_rate: 0.1 # perc of the difference
