kpxy: 0.50
kvxy: 0.30
kaxy: 1.0
kixy: 0.1

kpz: 0.4
kvz: 0.15
kaz: 1.0

km: 1.0

kixy_lim: 3.0
km_lim: 1.0 # [kg]

hover_thrust:
  a: 0.15369
  b: -0.23977

g : 9.8

max_tilt_angle: 45.0 # [deg]

yaw_offset: 0.0 # [deg]
