default_gains:

  horizontal:
    
    attitude:
      kq: 5.5
      kw: 0.0

  vertical:
    kp: 70.0
    kv: 40.0
    ka: 1.0

    attitude:
      kq: 1.0
      kw: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 5.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

gains_filter:
  filter_rate: 20 # [Hz]
  perc_change_rate: 1.0
  min_change_rate: 0.1 # perc of the difference
