kpxy: 0.50
kvxy: 0.30
kixy: 0.1

kpz: 0.5
kvz: 0.15

km: 1.0

kixy_lim: 3.0
km_lim: 1.0 # [kg]

hover_thrust:
  a: 0.12962
  b: -0.10624

g : 9.8

max_tilt_angle: 45.0 # [deg]

yaw_offset: 0.0 # [deg]
